# Application Name
spring.application.name=movie-ticket-booking

# Server Port
server.port=8080

# Database Configuration (Microsoft SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MovieTicketBooking;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# File Upload Limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Enable Lazy Initialization Outside Transaction
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

app.payment.bank-bin=970422       
app.payment.bank-name=MB Bank
app.payment.account-no=76621082005 
app.payment.account-name=NGUYEN HOANG LONG

# Upload Directory
app.upload.dir=uploads
